### ISSUE TITLE
[Feature]: Automatic slow mode based on channel activity

### ISSUE THREAD

**Issue by jonbarrow** [PretendoNetwork/chubby#15]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What feature do you want to see added?

Dynamically enable/disable slow mode based on how active a channel is.

### Why do you want to have this feature?

Many users in the Discord server complain about the constant slow mode. Having this be handled dynamically could serve as a good middle ground between managing messages and user activity.

### Any other details to share? (OPTIONAL)

This is not a very trivial issue to solve. There are multiple ways to go about this and it is very easy to get wrong.

**Comment by MatthewL246** [comment]
Closed by #30
