### ISSUE TITLE
[Bug]: Automod actions get logged incorrectly when using audit logs

### ISSUE THREAD

**Issue by jonbarrow** [PretendoNetwork/chubby#18]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What happened?

When the automod does actions like timing someone out, which the bot logs the incorrect user as having executed the action

### What did you expect to happen?

The bot to log that it was the automod. Time checks need to be added for all instances of audit log checking

### Steps to reproduce?

This happens because some checks the bot does rely on heuristics rather than data from Discord. For example when timing someone out, the generic "member updated" event is sent. The bot checks to see if `communicationDisabledUntilTimestamp` has been changed, and if so then it knows the update was for a timeout. To know who timed the user out, the bot will then check the audit log for the most recent `MEMBER_UPDATE` log, and use the executor of that in the log. However in this case a time check is not done on the audit log, and the automod does not create an audit log. So when an automod times a user out, the bot will pull the log for the most recent real user who timed someone out

**Comment by wolfendale** [comment]
Fixed by #20
