### ISSUE TITLE
[Feature]: Reaction log

### ISSUE THREAD

**Issue by wolfendale** [PretendoNetwork/chubby#19]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What feature do you want to see added?

Ability for moderators to see what reactions have been added to a message even if that reaction has been removed

### Why do you want to have this feature?

Some members use reactions to troll or otherwise antagonize people. However, if a user does this and then removes the reaction it can be difficult to tell who in the chat is doing this

**Comment by jonbarrow** [comment]
I'll approve this but if this gets logged in the same place as the other logs then it's going to become a NIGHTMARE to sift through

This should probably be done in another channel

Though I do worry about rate limits. There's 50,000 people in the server, which is a LOT of people doing reactions. We can very easily hit the Discord rate limit here which would potentially slow down other features which we wait for more requests to free up

**Comment by wolfendale** [comment]
My initial thoughts about this are that we only need to worry about when people remove a reaction which should be much less frequent than reactions. I think if it goes in just a log channel it'd need to be a separate one, but that might be annoying to search so I'm thinking about other options at the moment

**Comment by wolfendale** [comment]
Closed by #29
