### ISSUE TITLE
[Feature]: Simplified leveling system

### ISSUE THREAD

**Issue by MatthewL246** [PretendoNetwork/chubby#24]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What feature do you want to see added?

This would be a very simple leveling system that allows users to gain a "Trusted" role after they have contributed a certain amount to the server.

### Why do you want to have this feature?

Members are currently frustrated that they can't send media in the general channels, but we want to prevent trolls and raids from spamming images. Giving users media permissions only after they have contributed a certain amount to the server is a fair way to allow only users who can be trusted to send media.

### Any other details to share? (OPTIONAL)

This has been discussed internally in [Leveling system](https://discord.com/channels/408718485913468928/1259208575746838548).

**Comment by wolfendale** [comment]
Added by #25
