### ISSUE TITLE
[Feature]: Auto assign @ModPing role

### ISSUE THREAD

**Issue by wolfendale** [PretendoNetwork/chubby#28]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What feature do you want to see added?

We have a @ModPing role in the server that users can use to notify moderators who are available to respond to issues. This has been a useful tool for the mods but currently they have to manually assign/unassign the role.

They have asked that there be a mechanism that would allow the role to be assigned to them when they set their status to online and is removed when their status is set to something else, this would make it easier for them to opt in to pings in different circumstances.

### Why do you want to have this feature?

To better manage when mods are pinged

**Comment by MatthewL246** [comment]
Closed by #32
